export interface ExpositorResponse {
  id: number;
  nombre: string;
  profesion: null | string;
  nacionalidad: null | string;
  ciudad: null | string;
  radicatoria: null | string;
  telefono1: null | string;
  telefono2: null;
  fecha_nacimiento: string | null;
  tipo: null;
  foto: null | string;
  biografia: null | string;
  created_at: Date;
  updated_at: Date;
  deleted_at: null;
  pabellon: Pabellon;
  local: string;
  favorito: boolean;
  cantidad_fav: number;
}

export enum Pabellon {
  Bar = "bar",
  Brasil = "Brasil...",
  CulturalBolivia = "Cultural - Bolivia",
  CulturalParaguay = "Cultural - Paraguay",
  Usa = "USA",
}

// Generated by https://quicktype.io

export interface SalonFechaSalon {
  fecha: string;
  agendaS: AgendaSalon[];
}

export interface AgendaSalon {
  pabellon: string;
  expositor: string;
  profesion: null;
  id: number;
  titulo: string;
  expositor_id: number;
  salon_id: number;
  hora: string;
  fecha: Date;
  local: null;
  created_at: Date;
  updated_at: Date;
  deleted_at: null;
  foto: null;
  icono_salon: null;
  nacionalidad: null;
}

// Generated by https://quicktype.io

export interface AgendaFechaAgenda {
  fecha: string;
  agenda: Agenda[];
}

export interface Agenda {
  pabellon: string;
  expositor: string;
  profesion: null;
  id: number;
  titulo: string;
  expositor_id: number;
  salon_id: number;
  hora: string;
  fecha: string;
  local: null | string;
  created_at: string;
  updated_at: string;
  deleted_at: null | string;
  foto: null | string;
  icono_salon: null | string;
  nacionalidad: null | string;
}

export interface AgendaResponses {
  // Define una interfaz llamada AgendaResponses.
  fecha: number; // Define una propiedad llamada fecha de tipo número.
  fecha_completa: string; // Define una propiedad llamada fecha_completa de tipo cadena de texto.
  dia: string; // Define una propiedad llamada dia de tipo cadena de texto.
  mes: Mes; // Define una propiedad llamada mes de tipo Mes (enumeración).
}

export enum Mes { // Define una enumeración llamada Mes.
  Abril = "ABRIL", // Define un miembro de la enumeración llamado Abril con valor "ABRIL".
  Junio = "JUNIO", // Define un miembro de la enumeración llamado Junio con valor "JUNIO".
}

// Interfaz ParticipanteResponses generada por https://quicktype.io
export interface ParticipanteResponses {
  id: number; // Identificador único del participante (número)
  nombre: string; // Nombre del participante (cadena de caracteres)
  profesion: null | string; // Profesión del participante (puede ser una cadena de caracteres o null)
  nacionalidad: null | string; // Nacionalidad del participante (puede ser una cadena de caracteres o null)
  ciudad: null | string; // Ciudad del participante (puede ser una cadena de caracteres o null)
  radicatoria: null | string; // Radicatoria del participante (puede ser una cadena de caracteres o null)
  telefono1: null | string; // Teléfono principal del participante (puede ser una cadena de caracteres o null)
  telefono2: null | string; // Teléfono secundario del participante (puede ser una cadena de caracteres o null)
  fecha_nacimiento: null | string; // Fecha de nacimiento del participante (puede ser una cadena de caracteres o null)
  tipo: null | string; // Tipo de participante (puede ser una cadena de caracteres o null)
  foto: null | string; // URL de la foto del participante (puede ser una cadena de caracteres o null)
  biografia: null | string; // Biografía del participante (puede ser una cadena de caracteres o null)
  created_at: string; // Fecha de creación del participante (cadena de caracteres)
  updated_at: string; // Fecha de actualización del participante (cadena de caracteres)
  deleted_at: null; // Fecha de eliminación del participante (puede ser null)
}

// Interfaz ParticipanteIDParticipante generada por https://quicktype.io
export interface ParticipanteIDParticipante {
  id: number; // Identificador único del participante (número)
  nombre: string; // Nombre del participante (cadena de caracteres)
  profesion: string; // Profesión del participante (cadena de caracteres)
  nacionalidad: string; // Nacionalidad del participante (cadena de caracteres)
  ciudad: string; // Ciudad del participante (cadena de caracteres)
  radicatoria: string; // Radicatoria del participante (cadena de caracteres)
  telefono1: string; // Teléfono principal del participante (cadena de caracteres)
  telefono2: null; // Teléfono secundario del participante (puede ser null)
  fecha_nacimiento: string; // Fecha de nacimiento del participante (cadena de caracteres)
  tipo: null; // Tipo de participante (puede ser null)
  foto: string; // URL de la foto del participante (cadena de caracteres)
  biografia: string; // Biografía del participante (cadena de caracteres)
  created_at: string; // Fecha de creación del participante (cadena de caracteres)
  updated_at: string; // Fecha de actualización del participante (cadena de caracteres)
  deleted_at: null; // Fecha de eliminación del participante (puede ser null)
  salones: Salone[]; // Lista de salones asociados al participante (arreglo de objetos Salone)
  pabellones: Pabellone[]; // Lista de pabellones asociados al participante (arreglo de objetos Pabellone)
}

// Interfaz Pabellone
export interface Pabellone {
  pabellon: string; // Nombre del pabellón (cadena de caracteres)
  agenda: PabelloneAgenda[]; // Lista de eventos en la agenda del pabellón (arreglo de objetos PabelloneAgenda)
}

// Interfaz PabelloneAgenda
export interface PabelloneAgenda {
  stand: string; // Nombre del stand (cadena de caracteres)
}

// Interfaz Salone
export interface Salone {
  salon: string; // Nombre del salón (cadena de caracteres)
  agenda: SaloneAgenda[]; // Lista de eventos en la agenda del salón (arreglo de objetos SaloneAgenda)
}

// Interfaz SaloneAgenda
export interface SaloneAgenda {
  titulo: string; // Título del evento (cadena de caracteres)
  hora: string; // Hora del evento (cadena de caracteres)
  fecha: string; // Fecha del evento (cadena de caracteres)
}
